### ISSUE TITLE
Deploy Web Server

### ISSUE THREAD

**Issue by JustinStiffler** [481TravelApp/TravelApp#4]
Setup prod server, and get packages setup.

**Comment by SteeleND** [comment]
server is running at travel-lxp-01
Using SSH and BSU creds, any dev team members can login.
RHEL7 VM with the dotnet subscription added.

**Comment by SteeleND** [comment]
Web server is running, server is setup, having port issues, moving to next sprint

**Comment by SteeleND** [comment]
Webserver configured and setup, able to run a php website off of it. Visible to the outside world.
