### ISSUE TITLE
Integrate Boise State Authentication

### ISSUE THREAD

**Issue by JustinStiffler** [481TravelApp/TravelApp#6]
REFERENCES: #7 
Given a valid @boisetate.edu or @u.boisestate.edu email
When promoted by the page, and inputing the data above
User is Authorized to have a Boise State user and can access the applications landing page.

- [ ] Validate that given a @gmail address, we deny the user
- [ ] Validate that given the wrong password, with a @boisestate.edu email
- [ ] Site forwards the user to the home page of the travel application

**Comment by SteeleND** [comment]
REFERENCE: 
#7

**Comment by SteeleND** [comment]
We are going to have to build a personalized auth, with client side validation of 'boisestate.edu', we then pass the data to a socialite PHP library google auth. 

To avoid the issue of us not being able to get access to BSU single sign on, we will be doing a validation on client side, then when it passes, pass it to socialte to validate.
